/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author mat.aules
 */
public class FrmRegistre extends javax.swing.JDialog {
    
    private boolean _canviUser, _canviPas, _canviNom, _canviNac, _canviDia, _canviMes, _canviAny;

    /**
     * Creates new form FrmRegistre
     */
    public FrmRegistre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this._canviUser = false;
        this._canviPas = false;
        this._canviNom = false;
        this._canviNac = false;
        this._canviDia = false;
        this._canviMes = false;
        this._canviAny = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUser = new javax.swing.JTextField();
        txtPas = new javax.swing.JTextField();
        txtNom = new javax.swing.JTextField();
        txtNac = new javax.swing.JTextField();
        txtDia = new javax.swing.JTextField();
        txtMes = new javax.swing.JTextField();
        txtAny = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnCan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtUser.setText("Nom d'usuari");
        txtUser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtUserPropertyChange(evt);
            }
        });

        txtPas.setText("Password");
        txtPas.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPasPropertyChange(evt);
            }
        });

        txtNom.setText("Nom");
        txtNom.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNomPropertyChange(evt);
            }
        });

        txtNac.setText("Nacionalitat");
        txtNac.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtNacPropertyChange(evt);
            }
        });

        txtDia.setText("Dia");
        txtDia.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtDiaPropertyChange(evt);
            }
        });

        txtMes.setText("Mes");
        txtMes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtMesPropertyChange(evt);
            }
        });

        txtAny.setText("Any");
        txtAny.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtAnyPropertyChange(evt);
            }
        });

        jLabel1.setText("Data de naixament");

        btnOk.setText("Registrar-se");
        btnOk.setEnabled(false);

        btnCan.setText("Cancel·lar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNac)
                    .addComponent(txtNom)
                    .addComponent(txtUser)
                    .addComponent(txtPas))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtAny, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnOk)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCan))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtUserPropertyChange
        // TODO add your handling code here:
        this._canviUser = !this.txtUser.getText().equals("Nom d'usuari");

        if(this._canviUser && this._canviPas && this._canviNom && this._canviNac && this._canviDia && this._canviMes && this._canviAny) this.btnOk.setEnabled(true);
    }//GEN-LAST:event_txtUserPropertyChange

    private void txtPasPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPasPropertyChange
        // TODO add your handling code here:
        this._canviPas = !this.txtUser.getText().equals("Password");

        if(this._canviUser && this._canviPas && this._canviNom && this._canviNac && this._canviDia && this._canviMes && this._canviAny) this.btnOk.setEnabled(true);
    }//GEN-LAST:event_txtPasPropertyChange

    private void txtNomPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNomPropertyChange
        // TODO add your handling code here:
        this._canviNom = !this.txtUser.getText().equals("Nom");
        if(this._canviUser && this._canviPas && this._canviNom && this._canviNac && this._canviDia && this._canviMes && this._canviAny) this.btnOk.setEnabled(true);
    }//GEN-LAST:event_txtNomPropertyChange

    private void txtNacPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtNacPropertyChange
        // TODO add your handling code here:
        this._canviNac = !this.txtUser.getText().equals("Nacionalitat");

        if(this._canviUser && this._canviPas && this._canviNom && this._canviNac && this._canviDia && this._canviMes && this._canviAny) this.btnOk.setEnabled(true);
    }//GEN-LAST:event_txtNacPropertyChange

    private void txtDiaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtDiaPropertyChange
        // TODO add your handling code here:
        this._canviDia = !this.txtUser.getText().equals("Dia");
        System.out.println("hola");
        if(this._canviUser && this._canviPas && this._canviNom && this._canviNac && this._canviDia && this._canviMes && this._canviAny) this.btnOk.setEnabled(true);
    }//GEN-LAST:event_txtDiaPropertyChange

    private void txtMesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtMesPropertyChange
        // TODO add your handling code here:
        this._canviMes = !this.txtUser.getText().equals("Mes");

        if(this._canviUser && this._canviPas && this._canviNom && this._canviNac && this._canviDia && this._canviMes && this._canviAny) this.btnOk.setEnabled(true);
    }//GEN-LAST:event_txtMesPropertyChange

    private void txtAnyPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtAnyPropertyChange
        // TODO add your handling code here:
        this._canviAny = !this.txtUser.getText().equals("Any");

        if(this._canviUser && this._canviPas && this._canviNom && this._canviNac && this._canviDia && this._canviMes && this._canviAny) this.btnOk.setEnabled(true);
    }//GEN-LAST:event_txtAnyPropertyChange

  public String[] showDialog(){
      String [] s = new String[7];
      this.setVisible(false);
      this.dispose();
      return s;
  }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCan;
    private javax.swing.JButton btnOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtAny;
    private javax.swing.JTextField txtDia;
    private javax.swing.JTextField txtMes;
    private javax.swing.JTextField txtNac;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPas;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
