/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.TotSeries;
import Model.TotSeriesDades;
import javax.swing.JOptionPane;

/**
 *
 * @author mat.aules
 */
public class MenuInicial extends javax.swing.JFrame implements ClientObserver {
    
    
    private TotSeries _ctrl;
    private TotSeriesDades _model;
    private String _user;
    
    
    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
    }

    public MenuInicial(TotSeries controlador, TotSeriesDades model) {
        initComponents();
        this.setLocationRelativeTo(null);
        this._ctrl = controlador;
        this._model = model;
        _model.registerObserver((ClientObserver) this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titol = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        btnLog = new javax.swing.JButton();
        btnCat = new javax.swing.JButton();
        btnSor = new javax.swing.JButton();
        btnOut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TotSeries Aplicació");

        titol.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        titol.setForeground(new java.awt.Color(51, 0, 255));
        titol.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titol.setText("TOT SERIES");
        titol.setToolTipText("");

        userName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userName.setText("Usuari no logejat");
        userName.setFocusable(false);

        btnReg.setText("Registrar-se");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        btnLog.setText("Log In");
        btnLog.setPreferredSize(new java.awt.Dimension(91, 23));
        btnLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogActionPerformed(evt);
            }
        });

        btnCat.setText("Mirar catàleg");

        btnSor.setText("Sortir");
        btnSor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorActionPerformed(evt);
            }
        });

        btnOut.setText("Log Out");
        btnOut.setEnabled(false);
        btnOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnSor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(titol, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titol, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userName)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReg)
                    .addComponent(btnLog, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOut)
                .addGap(18, 18, 18)
                .addComponent(btnCat)
                .addGap(18, 18, 18)
                .addComponent(btnSor)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSorActionPerformed

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        // TODO add your handling code here:
        FrmRegistre frmRegistre = new FrmRegistre(this, true); 
        frmRegistre.setVisible(true);
        String[] s = frmRegistre.showDialog();
        
        if (s != null) {
            this._ctrl.registrarUsuari(s[0], s[1], s[2], s[3], s[4], s[5], s[6]);
        }
        else {
            JOptionPane.showMessageDialog(this,
            "No s'ha completat el registre.",
            "Procés Cancel·lat",
            JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnRegActionPerformed

    private void btnLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogActionPerformed
        // TODO add your handling code here:
        FrmLogin frmLogin = new FrmLogin(this,true); 
        frmLogin.setVisible(true);
        String[] s = frmLogin.showDialog();
        if(s == null){
            JOptionPane.showMessageDialog(this,
                    "Procés Cancel·lat",
                    "Procés Cancel·lat",
                    JOptionPane.WARNING_MESSAGE);
        }else{
            this._ctrl.logIn(s[0], s[1]);
        }
        
    }//GEN-LAST:event_btnLogActionPerformed

    private void btnOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOutActionPerformed
        // TODO add your handling code here:
        this._ctrl.logOut();
        this._user = "";
        this.userName.setText("Usuari no logejat");
        this.btnOut.setEnabled(false);
        this.btnLog.setEnabled(true);
        this.btnReg.setEnabled(true);
    }//GEN-LAST:event_btnOutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCat;
    private javax.swing.JButton btnLog;
    private javax.swing.JButton btnOut;
    private javax.swing.JButton btnReg;
    private javax.swing.JButton btnSor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel titol;
    private javax.swing.JLabel userName;
    // End of variables declaration//GEN-END:variables

    @Override
    public void updateClient() {
        this._user = this._model.getClient();
        this.userName.setText("Logejat com: "+ this._user);
        this.btnOut.setEnabled(true);
        this.btnLog.setEnabled(false);
        this.btnReg.setEnabled(false);
    }
}
